/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_aartest_HelloWorld */

#ifndef _Included_com_example_aartest_HelloWorld
#define _Included_com_example_aartest_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_aartest_HelloWorld
 * Method:    testGetString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_aartest_HelloWorld_testGetString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
